export default {
  index: "Introduction",
  "getting-started": "Getting Started",
  features: "Features",
  "what-is-homebrew": "What is Homebrew?",
  "brew-commands": "Brew Commands",
  troubleshooting: "Troubleshooting",
  security: "Security",
  architecture: "Architecture",
  development: "Development",
  roadmap: "Roadmap",
  changelog: "Changelog",
  faq: "FAQ",
  contributing: "Contributing",
};
